name: mishiWorkflow
on:
  push:
    branches:
    - main
permissions:
  id-token: write
  contents: write
jobs:
  FirstJob:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: FirstStep
        env:
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python CodeFile.py
      - name: Step2
        env:
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          echo " #Results are:" > report.md
          echo results.txt >> report.md
          echo '![](./ActualvsPredicted.png "Actual vs Predicted Plot")' > report.md
          cml comment create report.md